package vistas;

import controladores.*;
import controladores.exceptions.NonexistentEntityException;
import jakarta.persistence.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelos.*;
import vistas.CRUD.*;

/**
 *
 * @author Sebastián Candelas Quero
 */

public class vistaAutores extends javax.swing.JFrame {
    
    private EntityManagerFactory emf = Persistence.createEntityManagerFactory("uniPersistencia");;
    //VistasCrud
    private aniadirAutor aniadirAut;
    //Controladores de las clases
    private ctrlJpaAutor ctrlAutores = new ctrlJpaAutor(emf);
    private ctrlJpaCategoria ctrlCateg = new ctrlJpaCategoria(emf);
    private ctrlJpaLibro ctrlLibro = new ctrlJpaLibro(emf);
    //Modelos de las tablas
    private DefaultTableModel modelAutores = new DefaultTableModel();
    private DefaultTableModel modelLibros = new DefaultTableModel();
    
    
    public vistaAutores() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("CRUD Autores - Sebastián Candelas Quero");
        inicModelosTablas();
        inicModelComboBox();
        rellenarTablaAutores(ctrlAutores.obtenerAllAutores());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAutores = new javax.swing.JTable();
        jLabelAutoresCat = new javax.swing.JLabel();
        jComboBoxCateg = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableLibros = new javax.swing.JTable();
        jLabelCatg = new javax.swing.JLabel();
        jTextFieldCategLibro = new javax.swing.JTextField();
        jMenuBarAutores = new javax.swing.JMenuBar();
        jMenuVolver = new javax.swing.JMenu();
        jMenuAlta = new javax.swing.JMenu();
        jMenuBaja = new javax.swing.JMenu();
        jMenuMod = new javax.swing.JMenu();
        jMenuRefrescar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableAutores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nombre"
            }
        ));
        jTableAutores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableAutoresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableAutores);

        jLabelAutoresCat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelAutoresCat.setText("Autores con libros en la categoría: ");

        jComboBoxCateg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxCateg.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxCategItemStateChanged(evt);
            }
        });

        jTableLibros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableLibros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableLibrosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableLibros);

        jLabelCatg.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelCatg.setText("Categorías del libro seleccionado: ");

        jTextFieldCategLibro.setEditable(false);

        jMenuVolver.setText("Volver");
        jMenuVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuVolverMouseClicked(evt);
            }
        });
        jMenuBarAutores.add(jMenuVolver);

        jMenuAlta.setText("Alta");
        jMenuAlta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuAltaMouseClicked(evt);
            }
        });
        jMenuBarAutores.add(jMenuAlta);

        jMenuBaja.setText("Baja");
        jMenuBaja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuBajaMouseClicked(evt);
            }
        });
        jMenuBarAutores.add(jMenuBaja);

        jMenuMod.setText("Modificar");
        jMenuBarAutores.add(jMenuMod);

        jMenuRefrescar.setText("Refrescar");
        jMenuRefrescar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuRefrescarMouseClicked(evt);
            }
        });
        jMenuBarAutores.add(jMenuRefrescar);

        setJMenuBar(jMenuBarAutores);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelAutoresCat)
                        .addGap(60, 60, 60)
                        .addComponent(jComboBoxCateg, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelCatg)
                        .addGap(45, 45, 45)
                        .addComponent(jTextFieldCategLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAutoresCat)
                    .addComponent(jComboBoxCateg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCatg)
                    .addComponent(jTextFieldCategLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(143, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuVolverMouseClicked
        //Cerramos la venta autores
        dispose();
        //Creamos la nueva ventana principal y la mostramos
        Principal principal = new Principal();
        principal.setVisible(true);
    }//GEN-LAST:event_jMenuVolverMouseClicked

    private void jTableAutoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableAutoresMouseClicked
        if(jTableAutores.getSelectedRow() != -1){
            Set<Libro> colecLibros;
            int row = jTableAutores.getSelectedRow();
            Object idAutor = modelAutores.getValueAt(row, 0);
            colecLibros = ctrlAutores.obtenerLibrosAutor(idAutor);
            rellenarTablaLibros(colecLibros);
        }
    }//GEN-LAST:event_jTableAutoresMouseClicked

    private void jComboBoxCategItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxCategItemStateChanged
        String cat = "" + jComboBoxCateg.getSelectedItem();
        if(cat.equals("--Ninguna--")){
            rellenarTablaAutores(ctrlAutores.obtenerAllAutores());
        }else{
            rellenarTablaAutores(ctrlAutores.obtenerAutoresCateg(cat));
        }
    }//GEN-LAST:event_jComboBoxCategItemStateChanged

    private void jTableLibrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableLibrosMouseClicked
        if(jTableLibros.getSelectedRow() != -1){
            Set<Categoria> colecCategorias;
            int row = jTableLibros.getSelectedRow();
            Object nombreLi = modelLibros.getValueAt(row, 0);
            colecCategorias = ctrlLibro.obtenerCategoriasLibro(nombreLi);
            for(Categoria c : colecCategorias){
                jTextFieldCategLibro.setText(c.getNomCategoria() + "\n");
            }
        }
    }//GEN-LAST:event_jTableLibrosMouseClicked

    private void jMenuAltaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuAltaMouseClicked
        aniadirAut = new aniadirAutor(this, rootPaneCheckingEnabled);
        aniadirAut.setVisible(true);
    }//GEN-LAST:event_jMenuAltaMouseClicked

    private void jMenuRefrescarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuRefrescarMouseClicked
        rellenarTablaAutores(ctrlAutores.obtenerAllAutores());
        jComboBoxCateg.setSelectedIndex(0);
    }//GEN-LAST:event_jMenuRefrescarMouseClicked

    private void jMenuBajaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuBajaMouseClicked
        if(jTableAutores.getSelectedRow() == -1){
            JOptionPane.showMessageDialog(null, "Seleccione un autor de la tabla para dar de baja");
        }else{
            int selec = JOptionPane.showConfirmDialog(null, "¿Seguro que desea borrar el autor seleccionado?", "Confirmación", JOptionPane.YES_NO_OPTION);
            if(selec == JOptionPane.YES_OPTION){
                Object idAutor = modelAutores.getValueAt(jTableAutores.getSelectedRow(), 0);
                Autor autor = ctrlAutores.obtenerAutorXId(idAutor);
                if(autor.getLibrosSet().size() == 0){
                    JOptionPane.showMessageDialog(null, "No se pueden borrar autores que tengan libros");
                }else{
                    try {
                        ctrlAutores.baja(autor);
                    } catch (NonexistentEntityException ex) {
                        JOptionPane.showMessageDialog(null, "No se encuentra ningún autor que coincida");
                    }
                }
            }else{
                JOptionPane.showMessageDialog(null, "Baja cancelada");
            }
        
        }
    }//GEN-LAST:event_jMenuBajaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaAutores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaAutores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaAutores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaAutores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaAutores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBoxCateg;
    private javax.swing.JLabel jLabelAutoresCat;
    private javax.swing.JLabel jLabelCatg;
    private javax.swing.JMenu jMenuAlta;
    private javax.swing.JMenu jMenuBaja;
    private javax.swing.JMenuBar jMenuBarAutores;
    private javax.swing.JMenu jMenuMod;
    private javax.swing.JMenu jMenuRefrescar;
    private javax.swing.JMenu jMenuVolver;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableAutores;
    private javax.swing.JTable jTableLibros;
    private javax.swing.JTextField jTextFieldCategLibro;
    // End of variables declaration//GEN-END:variables

    private void inicModelosTablas() {
        //Tabla autores
        modelAutores.addColumn("Id");
        modelAutores.addColumn("Nombre");
        jTableAutores.setModel(modelAutores);
        //Tabla libros
        modelLibros.addColumn("Titulo");
        modelLibros.addColumn("Fecha Publicación");
        modelLibros.addColumn("Precio");
        jTableLibros.setModel(modelLibros);
        
    }

    private void rellenarTablaAutores(List<Autor> listaAutores) {
        modelAutores.setRowCount(0);
        for(Autor a : listaAutores){
            Object[] fila = {a.getIdAutor(), a.getNomAutor()};
            modelAutores.addRow(fila);
        }
    }

    private void rellenarTablaLibros(Set<Libro> colecLibros) {
        modelLibros.setRowCount(0);
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        for(Libro l : colecLibros){
            Object[] fila = {l.getTitulo(), sdf.format(l.getFechaPublicacion()), l.getPrecio()};
            modelLibros.addRow(fila);
        }
    }

    private void inicModelComboBox() {
        jComboBoxCateg.removeAllItems();
        jComboBoxCateg.addItem("--Ninguna--");
        for(Categoria c : ctrlCateg.obtenerCategorias()){
            jComboBoxCateg.addItem(c.getNomCategoria());
        }
    }
}
